In [2]:
import numpy as np

In [3]:
oceny = np.array([3.0, 4.0, 5.0, 3.5, 4.5])
print(oceny)

[3.  4.  5.  3.5 4.5]


In [4]:
type(oceny)

numpy.ndarray

In [5]:
oceny.shape

(5,)

In [6]:
print(oceny[0])
print(oceny[2])


3.0
5.0


In [7]:
print(oceny[1:4])

[4.  5.  3.5]


In [8]:
np.mean(oceny)

np.float64(4.0)

In [9]:
mediana = np.median(oceny)
minimum = np.min(oceny)
maksimum = np.max(oceny)
suma = np.sum(oceny)
odchylenie = np.std(oceny)

print(f"Mediana: {mediana}")
print(f"Minimum: {minimum}")
print(f"Maksimum: {maksimum}")
print(f"Suma: {suma}")
print(f"Odchylenie standardowe: {odchylenie:.2f}")

Mediana: 4.0
Minimum: 3.0
Maksimum: 5.0
Suma: 20.0
Odchylenie standardowe: 0.71


In [10]:
oceny_plus_jeden = oceny + 1
print(oceny_plus_jeden)
# Wynik: [4.  5.  6.  4.5 5.5]

[4.  5.  6.  4.5 5.5]


In [11]:
oceny_razy_trzy = oceny * 3
print(oceny_razy_trzy)
# Wynik: [ 9.  12.  15.  10.5 13.5]

[ 9.  12.  15.  10.5 13.5]


In [12]:
oceny[oceny > 4.0]

array([5. , 4.5])

In [13]:
wyniki = np.array([
[4.0, 3.5],
[5.0, 4.5],
[3.0, 4.0]
])
print(wyniki)

[[4.  3.5]
 [5.  4.5]
 [3.  4. ]]


In [14]:
# Sprawdzenie wymiarów tablicy NumPy
wymiary = oceny.shape
print(f"Liczba elementów (wierszy w wektorze 1D): {wymiary[0]}")

# Jeśli pracowałbyś na tabeli Pandas (DataFrame):
# wiersze, kolumny = df.shape
# print(f"Wiersze: {wiersze}, Kolumny: {kolumny}")

Liczba elementów (wierszy w wektorze 1D): 5


In [15]:
# Zakładając, że masz macierz, np. macierz = np.array([[3.0, 4.0, 5.0], [3.5, 4.5, 5.0]])
# Wyświetlenie: 1. wiersz (indeks 0), 2. kolumna (indeks 1)

element = macierz[0, 1]
print(f"Element z 1. wiersza i 2. kolumny to: {element}")

NameError: name 'macierz' is not defined

In [16]:
element = wyniki[0, 1]
print(f"Wynik studenta 0 z drugiego przedmiotu: {element}")

Wynik studenta 0 z drugiego przedmiotu: 3.5


In [17]:
srednia_przedmioty = np.mean(wyniki, axis=0)
srednia_studenci = np.mean(wyniki, axis=1)

print(f"Średnie wyniki z przedmiotów (kolumny): {srednia_przedmioty}")
print(f"Średnie wyniki poszczególnych studentów (wiersze): {srednia_studenci}")

Średnie wyniki z przedmiotów (kolumny): [4. 4.]
Średnie wyniki poszczególnych studentów (wiersze): [3.75 4.75 3.5 ]


In [18]:
liczba_elementow = wyniki.size
typ_danych = wyniki.dtype

In [19]:
print(f"Liczba elementów: {liczba_elementow}")
print(f"Typ danych: {typ_danych}")

Liczba elementów: 6
Typ danych: float64


In [20]:
srednia = np.mean(wyniki)
mediana = np.median(wyniki)
minimum = np.min(wyniki)
maksimum = np.max(wyniki)

In [21]:
print(f"Średnia: {srednia}")
print(f"Mediana: {mediana}")
print(f"Minimum: {minimum}")
print(f"Maksimum: {maksimum}")

Średnia: 4.0
Mediana: 4.0
Minimum: 3.0
Maksimum: 5.0


In [22]:
prog = 50
zdali = wyniki[wyniki >= prog]
nie_zdali = wyniki[wyniki < prog]
liczba_zdanych = zdali.size

print(f"Wyniki zaliczające: {zdali}")
print(f"Wyniki niezaliczające: {nie_zdali}")
print(f"Ilu studentów zdało: {liczba_zdanych}")

Wyniki zaliczające: []
Wyniki niezaliczające: [4.  3.5 5.  4.5 3.  4. ]
Ilu studentów zdało: 0


In [23]:
powyzej_sredniej = wyniki[wyniki > srednia]
ponizej_sredniej = wyniki[wyniki < srednia]

print(f"Wyniki > średnia: {powyzej_sredniej}")
print(f"Wyniki < średnia: {ponizej_sredniej}")

Wyniki > średnia: [5.  4.5]
Wyniki < średnia: [3.5 3. ]


In [24]:
wyniki = np.array([45, 88, 52, 30, 95, 67, 48, 72, 55, 12])

In [25]:
poprawione_wyniki = wyniki + 5

In [26]:
poprawione_wyniki = np.clip(poprawione_wyniki, 0, 100)

In [27]:
nowa_srednia = np.mean(poprawione_wyniki)

In [28]:
print(f"Poprawione wyniki: {poprawione_wyniki}")
print(f"Nowa średnia: {nowa_srednia}")

# --- 3.6. Klasyfikacja wyników (np.where) ---
# np.where(warunek, wartość_jeśli_prawda, wartość_jeśli_fałsz)
kategorie = np.where(poprawione_wyniki >= 85, 'bardzo dobry',
            np.where(poprawione_wyniki >= 70, 'dobry',
            np.where(poprawione_wyniki >= 50, 'dostateczny', 'niedostateczny')))

print(f"Kategorie: {kategorie}")

# --- 3.7. Wykrywanie nietypowych wyników ---
srednia_fin = np.mean(poprawione_wyniki)
outliers = poprawione_wyniki[poprawione_wyniki > 1.5 * srednia_fin]

print(f"Średnia końcowa: {srednia_fin}")
print(f"Potencjalne wartości odstające (outliers): {outliers}")

Poprawione wyniki: [ 50  93  57  35 100  72  53  77  60  17]
Nowa średnia: 61.4
Kategorie: ['dostateczny' 'bardzo dobry' 'dostateczny' 'niedostateczny'
 'bardzo dobry' 'dobry' 'dostateczny' 'dobry' 'dostateczny'
 'niedostateczny']
Średnia końcowa: 61.4
Potencjalne wartości odstające (outliers): [ 93 100]


In [32]:
import pandas as pd
df = pd.read_excel("Dane_testowe.xlsx")

In [33]:
print("--- Początek tabeli ---")
print(df.head())
print("\n--- Koniec tabeli ---")
print(df.tail())
print(f"\nRozmiar tabeli (wiersze, kolumny): {df.shape}")
print(f"\nNazwy kolumn: {df.columns.tolist()}")
print(f"\nTypy danych:\n{df.dtypes}")

--- Początek tabeli ---
   id_klienta   miasto    pakiet  wiek  sredni_rachunek kanal_kontaktu  \
0        1001   Poznan     Basic    20           749.72          email   
1        1002   Poznan     Basic    62           748.93        telefon   
2        1003  Rzeszow     Basic    32           296.30        telefon   
3        1004   Krakow  Standard    56           336.87        telefon   
4        1005   Lublin  Standard    28           280.84      aplikacja   

   czy_aktywny data_rejestracji  
0         True       2023-05-27  
1        False       2023-02-06  
2         True       2024-03-09  
3         True       2024-03-12  
4         True       2023-04-09  

--- Koniec tabeli ---
    id_klienta   miasto   pakiet  wiek  sredni_rachunek kanal_kontaktu  \
25        1026   Krakow    Basic    40           107.74          email   
26        1027  Rzeszow  Premium    59           141.46        telefon   
27        1028  Rzeszow  Premium    34           337.12        oddzial   
28      

In [34]:
print("\n--- Info o danych ---")
df.info()
print("\n--- Statystyki kolumn numerycznych ---")
print(df.describe())


--- Info o danych ---
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   id_klienta        30 non-null     int64  
 1   miasto            30 non-null     str    
 2   pakiet            30 non-null     str    
 3   wiek              30 non-null     int64  
 4   sredni_rachunek   30 non-null     float64
 5   kanal_kontaktu    30 non-null     str    
 6   czy_aktywny       30 non-null     bool   
 7   data_rejestracji  30 non-null     str    
dtypes: bool(1), float64(1), int64(2), str(4)
memory usage: 1.8 KB

--- Statystyki kolumn numerycznych ---
        id_klienta       wiek  sredni_rachunek
count    30.000000  30.000000        30.000000
mean   1015.500000  42.500000       495.734333
std       8.803408  13.472194       250.047957
min    1001.000000  20.000000       106.350000
25%    1008.250000  32.000000       327.540000
50%    1015.500000  41.5000

In [35]:
jedna_kolumna = df["wiek"]
kilka_kolumn = df[["miasto", "wiek", "sredni_rachunek"]]

In [36]:
pierwszy_wiersz = df.iloc[0]
piec_pierwszych = df.iloc[0:5]
fragment = df.iloc[2:7, 1:4] # wiersze 2-6, kolumny 1-3

In [37]:
print("\n--- Liczba wystąpień w kolumnie miasto ---")
print(df["miasto"].value_counts())


--- Liczba wystąpień w kolumnie miasto ---
miasto
Poznan      8
Krakow      7
Rzeszow     6
Gdansk      4
Lublin      3
Warszawa    2
Name: count, dtype: int64


In [38]:
print(f"\nŚredni rachunek: {df['sredni_rachunek'].mean():.2f}")
print(f"Mediana wieku: {df['wiek'].median()}")
print(f"Max rachunek: {df['sredni_rachunek'].max()}")


Średni rachunek: 495.73
Mediana wieku: 41.5
Max rachunek: 954.95


In [39]:
print(f"\nLiczba brakujących wartości:\n{df.isnull().sum()}")
print(f"Liczba zduplikowanych wierszy: {df.duplicated().sum()}")


Liczba brakujących wartości:
id_klienta          0
miasto              0
pakiet              0
wiek                0
sredni_rachunek     0
kanal_kontaktu      0
czy_aktywny         0
data_rejestracji    0
dtype: int64
Liczba zduplikowanych wierszy: 0


In [40]:
print("\n--- Średni rachunek wg miasta i pakietu ---")
grupa_miasto_pakiet = df.groupby(["miasto", "pakiet"])["sredni_rachunek"].mean()
print(grupa_miasto_pakiet)


--- Średni rachunek wg miasta i pakietu ---
miasto    pakiet  
Gdansk    Basic       418.025000
          Standard    511.505000
Krakow    Basic       381.120000
          Premium     618.125000
          Standard    333.195000
Lublin    Basic       434.935000
          Standard    280.840000
Poznan    Basic       725.613333
          Premium     552.670000
          Standard    350.510000
Rzeszow   Basic       567.366667
          Premium     239.290000
          Standard    492.990000
Warszawa  Basic       844.120000
          Premium     560.440000
Name: sredni_rachunek, dtype: float64


In [41]:
print("\n--- Losowe 7 rekordów ---")
print(df.sample(7))


--- Losowe 7 rekordów ---
    id_klienta   miasto    pakiet  wiek  sredni_rachunek kanal_kontaktu  \
20        1021   Gdansk  Standard    50           106.35      aplikacja   
10        1011   Krakow  Standard    43           329.52          email   
3         1004   Krakow  Standard    56           336.87        telefon   
25        1026   Krakow     Basic    40           107.74          email   
27        1028  Rzeszow   Premium    34           337.12        oddzial   
26        1027  Rzeszow   Premium    59           141.46        telefon   
22        1023   Gdansk     Basic    27           676.84          email   

    czy_aktywny data_rejestracji  
20        False       2023-09-07  
10        False       2023-03-03  
3          True       2024-03-12  
25         True       2023-01-12  
27         True       2023-05-20  
26         True       2023-12-09  
22        False       2024-06-28  


In [42]:
df = pd.read_excel("Dane_probne.xlsx")

In [43]:
print("1. Pierwsze 5 wierszy:\n", df.head(5))
print("\nOstatnie 3 wiersze:\n", df.tail(3))
print(f"\nLiczba wierszy i kolumn: {df.shape}")
print(f"Nazwy kolumn: {df.columns.tolist()}")

1. Pierwsze 5 wierszy:
    nr_uzytkownika  oddzial typ_uslugi  staz_lata  miesieczny_koszt  \
0            5001  RegionA      Start         11            989.10   
1            5002  RegionA     Biznes         13           1266.02   
2            5003  Centrum     Biznes          3            681.10   
3            5004   Polnoc     Biznes         13           1265.59   
4            5005   Polnoc      Start          3            660.53   

  zrodlo_zgloszenia  czy_przedluzyl data_startu  
0         formularz            True  2024-03-28  
1         infolinia            True  2023-08-23  
2           partner           False  2023-10-23  
3         formularz            True  2023-02-25  
4            portal            True  2024-03-26  

Ostatnie 3 wiersze:
     nr_uzytkownika   oddzial typ_uslugi  staz_lata  miesieczny_koszt  \
27            5028  Poludnie      Start          1            997.84   
28            5029    Polnoc     Biznes          6            973.17   
29            503

In [44]:
print("\n2. Kolumna oddzial:\n", df["oddzial"])
print("\nWybrane kolumny:\n", df[["oddzial", "typ_uslugi", "miesieczny_koszt"]])
print(f"\nTyp danych kolumny data_startu: {df['data_startu'].dtype}")


2. Kolumna oddzial:
 0      RegionA
1      RegionA
2      Centrum
3       Polnoc
4       Polnoc
5       Polnoc
6       Wschod
7       Wschod
8       Polnoc
9       Polnoc
10     Centrum
11      Wschod
12      Zachod
13      Polnoc
14     Centrum
15      Wschod
16     RegionA
17      Wschod
18     Centrum
19      Wschod
20     RegionA
21     RegionA
22    Poludnie
23     RegionA
24    Poludnie
25     RegionA
26      Polnoc
27    Poludnie
28      Polnoc
29      Polnoc
Name: oddzial, dtype: str

Wybrane kolumny:
      oddzial typ_uslugi  miesieczny_koszt
0    RegionA      Start            989.10
1    RegionA     Biznes           1266.02
2    Centrum     Biznes            681.10
3     Polnoc     Biznes           1265.59
4     Polnoc      Start            660.53
5     Polnoc      Start            122.87
6     Wschod     Biznes           1393.23
7     Wschod      Start            890.31
8     Polnoc     Expert            788.79
9     Polnoc      Start            911.40
10   Centrum      Sta

In [45]:
print("\n3. Pierwszy wiersz:\n", df.iloc[0])
print("\nWiersze 2-6:\n", df.iloc[1:6]) # indeksowanie od 0, więc 1:6 to wiersze 2,3,4,5,6
print("\nFragment 3-8 (wiersze) i 1-4 (kolumny):\n", df.iloc[2:8, 0:4])


3. Pierwszy wiersz:
 nr_uzytkownika             5001
oddzial                 RegionA
typ_uslugi                Start
staz_lata                    11
miesieczny_koszt          989.1
zrodlo_zgloszenia     formularz
czy_przedluzyl             True
data_startu          2024-03-28
Name: 0, dtype: object

Wiersze 2-6:
    nr_uzytkownika  oddzial typ_uslugi  staz_lata  miesieczny_koszt  \
1            5002  RegionA     Biznes         13           1266.02   
2            5003  Centrum     Biznes          3            681.10   
3            5004   Polnoc     Biznes         13           1265.59   
4            5005   Polnoc      Start          3            660.53   
5            5006   Polnoc      Start          7            122.87   

  zrodlo_zgloszenia  czy_przedluzyl data_startu  
1         infolinia            True  2023-08-23  
2           partner           False  2023-10-23  
3         formularz            True  2023-02-25  
4            portal            True  2024-03-26  
5            

In [46]:
print("\n4. Staz > 5 lat:\n", df[df["staz_lata"] > 5])
print("\nOddzial Centrum:\n", df[df["oddzial"] == "Centrum"])
print("\nStaz < 3 i przedluzyl:\n", df[(df["staz_lata"] < 3) & (df["czy_przedluzyl"] == True)])


4. Staz > 5 lat:
     nr_uzytkownika   oddzial typ_uslugi  staz_lata  miesieczny_koszt  \
0             5001   RegionA      Start         11            989.10   
1             5002   RegionA     Biznes         13           1266.02   
3             5004    Polnoc     Biznes         13           1265.59   
5             5006    Polnoc      Start          7            122.87   
6             5007    Wschod     Biznes         12           1393.23   
8             5009    Polnoc     Expert          8            788.79   
10            5011   Centrum      Start         10            910.71   
12            5013    Zachod      Start         11            978.52   
13            5014    Polnoc     Biznes         10           1447.94   
15            5016    Wschod      Start          8           1228.88   
16            5017   RegionA      Start         15            298.61   
17            5018    Wschod     Biznes         10            400.14   
20            5021   RegionA     Biznes      

In [47]:
sredni_koszt = df["miesieczny_koszt"].mean()
print(f"\n5. Średni koszt: {sredni_koszt:.2f}")
print(f"Min koszt: {df['miesieczny_koszt'].min()}")
print(f"Max koszt: {df['miesieczny_koszt'].max()}")
print("\nRekordy powyżej średniej:\n", df[df["miesieczny_koszt"] > sredni_koszt])


5. Średni koszt: 831.62
Min koszt: 122.87
Max koszt: 1447.94

Rekordy powyżej średniej:
     nr_uzytkownika   oddzial typ_uslugi  staz_lata  miesieczny_koszt  \
0             5001   RegionA      Start         11            989.10   
1             5002   RegionA     Biznes         13           1266.02   
3             5004    Polnoc     Biznes         13           1265.59   
6             5007    Wschod     Biznes         12           1393.23   
7             5008    Wschod      Start          1            890.31   
9             5010    Polnoc      Start          2            911.40   
10            5011   Centrum      Start         10            910.71   
11            5012    Wschod     Biznes          4           1010.74   
12            5013    Zachod      Start         11            978.52   
13            5014    Polnoc     Biznes         10           1447.94   
14            5015   Centrum     Biznes          3           1361.23   
15            5016    Wschod      Start       

In [48]:
df_staz_rosnaco = df.sort_values("staz_lata")
df_koszt_malejaco = df.sort_values("miesieczny_koszt", ascending=False)
print("\n6. Top 5 najdroższych usług:\n", df_koszt_malejaco.head(5))


6. Top 5 najdroższych usług:
     nr_uzytkownika  oddzial typ_uslugi  staz_lata  miesieczny_koszt  \
13            5014   Polnoc     Biznes         10           1447.94   
6             5007   Wschod     Biznes         12           1393.23   
14            5015  Centrum     Biznes          3           1361.23   
18            5019  Centrum     Biznes          5           1324.10   
1             5002  RegionA     Biznes         13           1266.02   

   zrodlo_zgloszenia  czy_przedluzyl data_startu  
13         formularz            True  2023-09-16  
6             portal            True  2023-08-23  
14         formularz            True  2024-02-23  
18         formularz            True  2024-04-18  
1          infolinia            True  2023-08-23  


In [49]:
print("\n7. Liczba typ_uslugi:\n", df["typ_uslugi"].value_counts())
oddzialy_count = df["oddzial"].value_counts()
print("\nLiczba oddzialow:\n", oddzialy_count)
print(f"Najczęstszy oddział: {oddzialy_count.idxmax()}")


7. Liczba typ_uslugi:
 typ_uslugi
Start     15
Biznes    13
Expert     2
Name: count, dtype: int64

Liczba oddzialow:
 oddzial
Polnoc      9
RegionA     7
Wschod      6
Centrum     4
Poludnie    3
Zachod      1
Name: count, dtype: int64
Najczęstszy oddział: Polnoc


In [51]:
df["koszt_po_podwyzce"] = df["miesieczny_koszt"] * 1.20
print("\n8. Pierwsze 5 wierszy z podwyżką:\n", df.head(5))
print("\nNowy koszt > 1200:\n", df[df["koszt_po_podwyzce"] > 1200])


8. Pierwsze 5 wierszy z podwyżką:
    nr_uzytkownika  oddzial typ_uslugi  staz_lata  miesieczny_koszt  \
0            5001  RegionA      Start         11            989.10   
1            5002  RegionA     Biznes         13           1266.02   
2            5003  Centrum     Biznes          3            681.10   
3            5004   Polnoc     Biznes         13           1265.59   
4            5005   Polnoc      Start          3            660.53   

  zrodlo_zgloszenia  czy_przedluzyl data_startu  koszt_po_podwyzce  
0         formularz            True  2024-03-28           1186.920  
1         infolinia            True  2023-08-23           1519.224  
2           partner           False  2023-10-23            817.320  
3         formularz            True  2023-02-25           1518.708  
4            portal            True  2024-03-26            792.636  

Nowy koszt > 1200:
     nr_uzytkownika  oddzial typ_uslugi  staz_lata  miesieczny_koszt  \
1             5002  RegionA     Bizne

In [52]:
sredni_typ = df.groupby("typ_uslugi")["miesieczny_koszt"].mean()
sredni_oddzial = df.groupby("oddzial")["miesieczny_koszt"].mean()
print("\n9. Średni koszt wg usługi:\n", sredni_typ)
print(f"Usługa z najwyższą średnią: {sredni_typ.idxmax()}")


9. Średni koszt wg usługi:
 typ_uslugi
Biznes    1035.339231
Expert     619.425000
Start      683.358667
Name: miesieczny_koszt, dtype: float64
Usługa z najwyższą średnią: Biznes


In [53]:
print("\n10. Braki danych:\n", df.isnull().sum())
print(f"Liczba duplikatów: {df.duplicated().sum()}")


10. Braki danych:
 nr_uzytkownika       0
oddzial              0
typ_uslugi           0
staz_lata            0
miesieczny_koszt     0
zrodlo_zgloszenia    0
czy_przedluzyl       0
data_startu          0
koszt_po_podwyzce    0
dtype: int64
Liczba duplikatów: 0


In [54]:
print("\n11. 5 najwyższych kosztów:\n", df.nlargest(5, "miesieczny_koszt"))
print("\n5 najniższych kosztów:\n", df.nsmallest(5, "miesieczny_koszt"))
print("\nLosowe 4 rekordy:\n", df.sample(4))


11. 5 najwyższych kosztów:
     nr_uzytkownika  oddzial typ_uslugi  staz_lata  miesieczny_koszt  \
13            5014   Polnoc     Biznes         10           1447.94   
6             5007   Wschod     Biznes         12           1393.23   
14            5015  Centrum     Biznes          3           1361.23   
18            5019  Centrum     Biznes          5           1324.10   
1             5002  RegionA     Biznes         13           1266.02   

   zrodlo_zgloszenia  czy_przedluzyl data_startu  koszt_po_podwyzce  
13         formularz            True  2023-09-16           1737.528  
6             portal            True  2023-08-23           1671.876  
14         formularz            True  2024-02-23           1633.476  
18         formularz            True  2024-04-18           1588.920  
1          infolinia            True  2023-08-23           1519.224  

5 najniższych kosztów:
     nr_uzytkownika  oddzial typ_uslugi  staz_lata  miesieczny_koszt  \
5             5006   Polnoc 

In [55]:
sredni_przedluzenie = df.groupby("czy_przedluzyl")["miesieczny_koszt"].mean()
print("\n12. Średni koszt vs przedłużenie:\n", sredni_przedluzenie)
wyzsza_grupa = "przedłużyli" if sredni_przedluzenie[True] > sredni_przedluzenie[False] else "nie przedłużyli"
print(f"Odpowiedź: Wyższy średni koszt ma grupa, która {wyzsza_grupa}.")


12. Średni koszt vs przedłużenie:
 czy_przedluzyl
False    724.026667
True     903.351111
Name: miesieczny_koszt, dtype: float64
Odpowiedź: Wyższy średni koszt ma grupa, która przedłużyli.


In [56]:
df.to_excel("wynik.xlsx", index=False)
df.to_csv("wynik.csv", index=False)



13. Dane zostały zapisane do plików wynik.xlsx i wynik.csv


In [57]:
import pandas as pd

df = pd.read_excel("Dane_probne.xlsx")


najlepszy_oddzial = df.groupby("oddzial")["miesieczny_koszt"].mean().idxmax()
print(f"Oddział z najwyższym średnim kosztem: {najlepszy_oddzial}")
df_filtered = df[df["oddzial"] == najlepszy_oddzial]
print(f"\nRekordy z oddziału {najlepszy_oddzial}:")
print(df_filtered)
liczba_przedluzonych = df_filtered[df_filtered["czy_przedluzyl"] == True].shape[0]
print(f"\nLiczba osób, które przedłużyły usługę w tym oddziale: {liczba_przedluzonych}")
df_filtered = df_filtered.copy() 
df_filtered["koszt_po_podwyzce_10"] = df_filtered["miesieczny_koszt"] * 1.10
ile_powyzej_1000 = df_filtered[df_filtered["koszt_po_podwyzce_10"] > 1000].shape[0]
print(f"Liczba rekordów z kosztem > 1000 po podwyżce: {ile_powyzej_1000}")
print("\n3 rekordy z najwyższym kosztem po podwyżce:")
print(df_filtered.nlargest(3, "koszt_po_podwyzce_10"))

Oddział z najwyższym średnim kosztem: Centrum

Rekordy z oddziału Centrum:
    nr_uzytkownika  oddzial typ_uslugi  staz_lata  miesieczny_koszt  \
2             5003  Centrum     Biznes          3            681.10   
10            5011  Centrum      Start         10            910.71   
14            5015  Centrum     Biznes          3           1361.23   
18            5019  Centrum     Biznes          5           1324.10   

   zrodlo_zgloszenia  czy_przedluzyl data_startu  
2            partner           False  2023-10-23  
10         formularz           False  2024-07-29  
14         formularz            True  2024-02-23  
18         formularz            True  2024-04-18  

Liczba osób, które przedłużyły usługę w tym oddziale: 2
Liczba rekordów z kosztem > 1000 po podwyżce: 3

3 rekordy z najwyższym kosztem po podwyżce:
    nr_uzytkownika  oddzial typ_uslugi  staz_lata  miesieczny_koszt  \
14            5015  Centrum     Biznes          3           1361.23   
18            5019  Ce