In [32]:
import numpy as np

In [33]:
oceny = np.array([3.0, 4.0, 5.0, 3.5, 4.5])
print(oceny)

[3.  4.  5.  3.5 4.5]


In [34]:
type(oceny)

numpy.ndarray

In [35]:
oceny.shape

(5,)

In [36]:
print(oceny[0])
print(oceny[2])


3.0
5.0


In [37]:
print(oceny[1:4])

[4.  5.  3.5]


In [38]:
np.mean(oceny)

np.float64(4.0)

In [39]:
mediana = np.median(oceny)
minimum = np.min(oceny)
maksimum = np.max(oceny)
suma = np.sum(oceny)
odchylenie = np.std(oceny)

print(f"Mediana: {mediana}")
print(f"Minimum: {minimum}")
print(f"Maksimum: {maksimum}")
print(f"Suma: {suma}")
print(f"Odchylenie standardowe: {odchylenie:.2f}")

Mediana: 4.0
Minimum: 3.0
Maksimum: 5.0
Suma: 20.0
Odchylenie standardowe: 0.71


In [40]:
oceny_plus_jeden = oceny + 1
print(oceny_plus_jeden)
# Wynik: [4.  5.  6.  4.5 5.5]

[4.  5.  6.  4.5 5.5]


In [41]:
oceny_razy_trzy = oceny * 3
print(oceny_razy_trzy)
# Wynik: [ 9.  12.  15.  10.5 13.5]

[ 9.  12.  15.  10.5 13.5]


In [42]:
oceny[oceny > 4.0]

array([5. , 4.5])

In [43]:
wyniki = np.array([
[4.0, 3.5],
[5.0, 4.5],
[3.0, 4.0]
])
print(wyniki)

[[4.  3.5]
 [5.  4.5]
 [3.  4. ]]


In [44]:
# Sprawdzenie wymiarów tablicy NumPy
wymiary = oceny.shape
print(f"Liczba elementów (wierszy w wektorze 1D): {wymiary[0]}")

# Jeśli pracowałbyś na tabeli Pandas (DataFrame):
# wiersze, kolumny = df.shape
# print(f"Wiersze: {wiersze}, Kolumny: {kolumny}")

Liczba elementów (wierszy w wektorze 1D): 5


In [45]:
# Zakładając, że masz macierz, np. macierz = np.array([[3.0, 4.0, 5.0], [3.5, 4.5, 5.0]])
# Wyświetlenie: 1. wiersz (indeks 0), 2. kolumna (indeks 1)

element = macierz[0, 1]
print(f"Element z 1. wiersza i 2. kolumny to: {element}")

NameError: name 'macierz' is not defined

In [46]:
element = wyniki[0, 1]
print(f"Wynik studenta 0 z drugiego przedmiotu: {element}")

Wynik studenta 0 z drugiego przedmiotu: 3.5


In [47]:
srednia_przedmioty = np.mean(wyniki, axis=0)
srednia_studenci = np.mean(wyniki, axis=1)

print(f"Średnie wyniki z przedmiotów (kolumny): {srednia_przedmioty}")
print(f"Średnie wyniki poszczególnych studentów (wiersze): {srednia_studenci}")

Średnie wyniki z przedmiotów (kolumny): [4. 4.]
Średnie wyniki poszczególnych studentów (wiersze): [3.75 4.75 3.5 ]


In [48]:
liczba_elementow = wyniki.size
typ_danych = wyniki.dtype

In [49]:
print(f"Liczba elementów: {liczba_elementow}")
print(f"Typ danych: {typ_danych}")

Liczba elementów: 6
Typ danych: float64


In [50]:
srednia = np.mean(wyniki)
mediana = np.median(wyniki)
minimum = np.min(wyniki)
maksimum = np.max(wyniki)

In [51]:
print(f"Średnia: {srednia}")
print(f"Mediana: {mediana}")
print(f"Minimum: {minimum}")
print(f"Maksimum: {maksimum}")

Średnia: 4.0
Mediana: 4.0
Minimum: 3.0
Maksimum: 5.0


In [52]:
prog = 50
zdali = wyniki[wyniki >= prog]
nie_zdali = wyniki[wyniki < prog]
liczba_zdanych = zdali.size

print(f"Wyniki zaliczające: {zdali}")
print(f"Wyniki niezaliczające: {nie_zdali}")
print(f"Ilu studentów zdało: {liczba_zdanych}")

Wyniki zaliczające: []
Wyniki niezaliczające: [4.  3.5 5.  4.5 3.  4. ]
Ilu studentów zdało: 0


In [53]:
powyzej_sredniej = wyniki[wyniki > srednia]
ponizej_sredniej = wyniki[wyniki < srednia]

print(f"Wyniki > średnia: {powyzej_sredniej}")
print(f"Wyniki < średnia: {ponizej_sredniej}")

Wyniki > średnia: [5.  4.5]
Wyniki < średnia: [3.5 3. ]


In [54]:
wyniki = np.array([45, 88, 52, 30, 95, 67, 48, 72, 55, 12])

In [55]:
poprawione_wyniki = wyniki + 5

In [56]:
poprawione_wyniki = np.clip(poprawione_wyniki, 0, 100)

In [57]:
nowa_srednia = np.mean(poprawione_wyniki)

In [58]:
print(f"Poprawione wyniki: {poprawione_wyniki}")
print(f"Nowa średnia: {nowa_srednia}")

# --- 3.6. Klasyfikacja wyników (np.where) ---
# np.where(warunek, wartość_jeśli_prawda, wartość_jeśli_fałsz)
kategorie = np.where(poprawione_wyniki >= 85, 'bardzo dobry',
            np.where(poprawione_wyniki >= 70, 'dobry',
            np.where(poprawione_wyniki >= 50, 'dostateczny', 'niedostateczny')))

print(f"Kategorie: {kategorie}")

# --- 3.7. Wykrywanie nietypowych wyników ---
srednia_fin = np.mean(poprawione_wyniki)
outliers = poprawione_wyniki[poprawione_wyniki > 1.5 * srednia_fin]

print(f"Średnia końcowa: {srednia_fin}")
print(f"Potencjalne wartości odstające (outliers): {outliers}")

Poprawione wyniki: [ 50  93  57  35 100  72  53  77  60  17]
Nowa średnia: 61.4
Kategorie: ['dostateczny' 'bardzo dobry' 'dostateczny' 'niedostateczny'
 'bardzo dobry' 'dobry' 'dostateczny' 'dobry' 'dostateczny'
 'niedostateczny']
Średnia końcowa: 61.4
Potencjalne wartości odstające (outliers): [ 93 100]


In [59]:
df = pd.read_excel("Dane_testowe.xlsx")

NameError: name 'pd' is not defined

In [64]:
import pandas as pd 

In [ ]:
df = pd.read_excel("Dane_testowe.xlsx")
print(df)